### ISSUE TITLE
Why does Bowerphp require symfony?

### ISSUE THREAD

**Issue by KG20** [Bee-Lab/bowerphp#163]
I am sorry if these are stupid questions (newbie here), but:
 why does bowerphp require symfony?
if I am not using symfony should I still use this?
if i need to include each script from bower-component folder separately (unlike composer); what are the advantages of using this?

Thanks for your help in advance!

**Comment by garak** [comment]
Likely it's not clear to you what Symfony is. As you can see on official website "Symfony is a set of reusable PHP components". So, you're already using Symfony, just because you're using composer (that is using Symfony just like bowerphp does).
I'm not sure to understand your question about including each script...

**Comment by KG20** [comment]
oh, ok! Sorry about the misunderstanding. What I meant to ask is, for different javascript files, I should include each file I want to use in <script> tags right? like, <script src="../bower_components/somefile.js></script> right?

**Comment by garak** [comment]
Yes, bowerphp (like bower) doesn't do any post processing to your assets. If you look for something like that, see webpack (but you'll need node)

**Comment by KG20** [comment]
Thanks!
